server:
  port: 8081
spring:
  application:
    name: mq_provider
  rabbitmq:
    host: 47.99.170.248
    port: 5672
    username: admin
    password: admin
    connection-timeout: 15000
    #开启confirm机制
    publisher-confirm-type: correlated
    #开启returns
    publisher-returns: true


